[package]
name = "server-workspace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mc-varint = "0.1.1"
mio = { version = "0.8.10", features = ["os-poll", "net"] }
