use crate::{
    io::prelude::{Decoder, Encoder},
    net::prelude::PacketHandler,
    protocol::{
        macros::{packet_id, protocol, protocol_server, receiving_packets},
        v1_20_4::configuration::acknowledge_finish_configuration::AcknowledgeFinishConfiguration,
    },
    server::{
        chunk::Chunk,
        prelude::{GamePlayer, GameServer},
    },
};

use super::{
    configuration::{
        client_information::{ClientInformation, ClientInformationConf, ClientInformationPlay},
        feature_flags::FeatureFlags,
        finish_configuration::{FinishConfigurationC2s, FinishConfigurationS2c},
        plugin_message::{
            PluginMessage, PluginMessageConfC2s, PluginMessageConfS2c, PluginMessagePlayC2s,
            PluginMessagePlayS2c,
        },
        registry::RegistryData,
        server_data::ServerData,
        update_tags::UpdateTags,
    },
    login::{
        login_acknowledged::LoginAcknowledged, login_play::LoginPlay, login_start::LoginStart,
        login_success::LoginSuccess, set_compression::SetCompression,
    },
    play::{
        change_difficulty::S2CChangeDifficulty,
        keep_alive::{KeepAliveConfC2s, KeepAliveConfS2c, KeepAlivePlayC2s, KeepAlivePlayS2c},
        player_abilities::PlayerAbilities,
        player_info::PlayerInfoUpdate,
        set_center_chunk::SetCenterChunk,
        set_container_contents::SetContainerContent,
        set_container_property::SetContainerProperty,
        set_container_slot::SetContainerSlot,
        set_default_position::SetDefaultPosition,
        set_entity_metadata::SetEntityMetadata,
        set_health::SetHealth,
        set_held_item::{C2SSetHeldItem, S2CSetHeldItem, SetHeldItem},
        set_render_distance::SetRenderDistance,
        set_simulation_distance::SetSimulationDistance,
        synchronize_player_position::SyncPlayerPosition,
        system_chat_message::SystemChatMessage,
        update_attributes::UpdateAttributes,
        update_light::UpdateLight,
        update_time::UpdateTime,
    },
    status::{PingRequest, PingResponse, StatusRequest, StatusResponse},
};
use crate::server::prelude::ConnectionState::*;

pub struct MinecraftServerV1_20_4;
protocol!(MinecraftServerV1_20_4, 765);

packet_id!(
    (0x00, super::handshake::HandShake),
    (0x00, StatusResponse<'_>),
    (0x00, StatusRequest),
    (0x01, PingRequest),
    (0x01, PingResponse),
    (0x00, LoginStart),
    (0x03, SetCompression),
    (0x02, LoginSuccess),
    (0x03, LoginAcknowledged),
    (0x00, ClientInformationConf),
    (0x09, ClientInformationPlay),
    (0x09, UpdateTags),
    (0x18, PluginMessagePlayS2c),
    (0x00, PluginMessageConfS2c),
    (0x10, PluginMessagePlayC2s),
    (0x01, PluginMessageConfC2s),
    (0x02, FinishConfigurationS2c),
    (0x02, FinishConfigurationC2s),
    (0x08, FeatureFlags),
    (0x3E, SyncPlayerPosition),
    (0x62, UpdateTime),
    (0x71, UpdateAttributes),
    (0x52, SetCenterChunk),
    (0x60, SetSimulationDistance),
    (0x53, SetRenderDistance),
    (0x3C, PlayerInfoUpdate),
    (0x49, ServerData),
    (0x54, SetDefaultPosition),
    (0x2C, C2SSetHeldItem),
    (0x51, S2CSetHeldItem),
    (0x36, PlayerAbilities),
    (0x05, RegistryData),
    (0x29, LoginPlay),
    (0x13, SetContainerContent),
    (0x14, SetContainerProperty),
    (0x15, SetContainerSlot),
    (0x56, SetEntityMetadata),
    (0x5B, SetHealth),
    (0x0B, S2CChangeDifficulty),
    (0x25, Chunk),
    (0x69, SystemChatMessage),
    (0x15, KeepAlivePlayC2s),
    (0x03, KeepAliveConfS2c),
    (0x24, KeepAlivePlayS2c),
    (0x03, KeepAliveConfC2s),
    (0x28, UpdateLight),
    (0x02, AcknowledgeFinishConfiguration),
);

receiving_packets!(
    MinecraftServerV1_20_4,
    (HandShake, super::handshake::HandShake),
    (Status, StatusRequest),
    (Status, PingRequest),
    (Login, LoginStart),
    (Login, LoginAcknowledged),
    (Confgiuration, ClientInformationConf),
    (Play, ClientInformationPlay),
    (Play, PluginMessagePlayC2s),
    (Confgiuration, PluginMessageConfC2s),
    (Confgiuration, FinishConfigurationC2s),
    //(Play, C2SSetHeldItem),
    (Play, KeepAlivePlayC2s),
    (Confgiuration, AcknowledgeFinishConfiguration),
);
